### ISSUE TITLE
编译成功，跳转播放页面崩溃

### ISSUE THREAD

**Issue by ZhangGengTao** [Yuye584312311/IMusic#27]
在播放得xml增加以下代码：
 <com.video.player.lib.view.VideoPlayerTrackView
        android:id="@+id/video_track"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        app:video_autoSetCoverController="true"
        app:video_autoSetVideoController="true"/>
        
 编译后跳转到页面报以下错误(是否需要全局初始化？项目未体现)：
        Caused by: android.view.InflateException: Binary XML file line #15 in com.zszs.activity:layout/activity_test: Binary XML file line #15 in com.zszs.activity:layout/activity_test: Error inflating class com.video.player.lib.view.VideoPlayerTrackView
Caused by: android.view.InflateException: Binary XML file line #15 in com.zszs.activity:layout/activity_test: Error inflating class com.video.player.lib.view.VideoPlayerTrackView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:470)
	at android.app.Activity.setContentView(Activity.java:3337)
	at com.zszs.activity.TestActivity.onCreate(TestActivity.kt:37)
	at android.app.Activity.performCreate(Activity.java:7815)
	at android.app.Activity.performCreate(Activity.java:7804)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1325)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3350)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3514)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.view.InflateException: Binary XML file line #23 in com.zszs.activity:layout/video_default_controller_layout: Binary XML file line #23 in com.zszs.activity:layout/video_default_controller_layout: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #23 in com.zszs.activity:layout/video_default_controller_layout: Error inflating class <unknown>

**Comment by hty527** [comment]
你好，非常感谢你的反馈！此项目不再维护。如有需要请使用：https://github.com/hty527/iPlayer
